basePath: /api
definitions:
  add_skill.request:
    properties:
      about:
        example: I am Groot
        type: string
      category_id:
        example: 1
        type: integer
      video_card_link:
        example: https://youtu.be/HIcSWuKMwOw?si=FtxN1QJU9ZWnXy85
        type: string
    required:
    - category_id
    type: object
  get_categories.category:
    description: data of category
    properties:
      id:
        example: 1
        type: integer
      min_age:
        example: 12
        type: integer
      name:
        example: Programing
        type: string
    type: object
  get_categories.response:
    description: get categories response
    properties:
      categories:
        items:
          $ref: '#/definitions/get_categories.category'
        type: array
    type: object
  get_teacher.response:
    properties:
      birthdate:
        example: "2002-09-09T10:10:10+09:00"
        type: string
      email:
        example: qwerty@example.com
        type: string
      name:
        example: John
        type: string
      registration_date:
        example: "2022-09-09T10:10:10+09:00"
        type: string
      skills:
        items:
          $ref: '#/definitions/get_teacher.skill'
        type: array
      surname:
        example: Smith
        type: string
      teacher_id:
        example: 1
        type: integer
      user_id:
        example: 1
        type: integer
    type: object
  get_teacher.skill:
    properties:
      about:
        example: about me...
        type: string
      category_id:
        example: 1
        type: integer
      rate:
        example: 5
        type: integer
      skill_id:
        example: 1
        type: integer
      video_card_link:
        example: https://youtu.be/HIcSWuKMwOw?si=FtxN1QJU9ZWnXy85
        type: string
    type: object
  get_teachers.response:
    properties:
      teachers:
        items:
          $ref: '#/definitions/get_teachers.teacher'
        type: array
    type: object
  get_teachers.skill:
    properties:
      about:
        example: about me...
        type: string
      category_id:
        example: 1
        type: integer
      category_name:
        example: Category
        type: string
      rate:
        example: 5
        type: integer
      skill_id:
        example: 1
        type: integer
      video_card_link:
        example: https://youtu.be/HIcSWuKMwOw?si=FtxN1QJU9ZWnXy85
        type: string
    type: object
  get_teachers.teacher:
    properties:
      birthdate:
        example: "2002-09-09T10:10:10+09:00"
        type: string
      email:
        example: qwerty@example.com
        type: string
      name:
        example: John
        type: string
      registration_date:
        example: "2022-09-09T10:10:10+09:00"
        type: string
      skills:
        items:
          $ref: '#/definitions/get_teachers.skill'
        type: array
      surname:
        example: Smith
        type: string
      teacher_id:
        example: 1
        type: integer
      user_id:
        example: 1
        type: integer
    type: object
  get_user.response:
    properties:
      birthdate:
        example: "2002-09-09T10:10:10+09:00"
        type: string
      email:
        example: qwerty@example.com
        type: string
      id:
        example: 1
        type: integer
      is_teacher:
        example: false
        type: boolean
      name:
        example: John
        type: string
      registration_date:
        example: "2022-09-09T10:10:10+09:00"
        type: string
      surname:
        example: Smith
        type: string
    type: object
  jsonutils.ErrorStruct:
    properties:
      error:
        type: string
    type: object
  login.request:
    properties:
      email:
        example: john@gmail.com
        type: string
      password:
        example: strongpass123
        type: string
    required:
    - email
    - password
    type: object
  login.response:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  registration.request:
    description: User registration request
    properties:
      birthdate:
        example: "2000-01-01T00:00:00Z"
        type: string
      email:
        example: john@gmail.com
        type: string
      name:
        example: John
        type: string
      password:
        example: strongpass123
        type: string
      surname:
        example: Smith
        type: string
    required:
    - birthdate
    - email
    - name
    - password
    - surname
    type: object
  registration.response:
    description: User registration response
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
host: localhost:81
info:
  contact:
    email: ruslanrbb8@gmail.com
    name: Ruslan's Support
    url: https://t.me/Ruslan20007
  description: back-end part for mobile application.
  title: Learn-Share API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/login.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      summary: Login user
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Register a new user (student) in the system
      parameters:
      - description: Registration Info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/registration.request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/registration.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      summary: Register new user
      tags:
      - auth
  /categories:
    get:
      description: Get list of all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/get_categories.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      summary: Get categories
      tags:
      - categories
  /teacher:
    get:
      description: Get all info about teacher (user info + teacher + his skills) by
        user id in token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/get_teacher.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      security:
      - BearerAuth: []
      summary: Get teacher data
      tags:
      - teachers
    post:
      description: Get user id by jwt token, and he became teach (if he was not be
        registrate himself as teacher)
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      security:
      - BearerAuth: []
      summary: User registrate also as teacher
      tags:
      - teachers
  /teacher/skill:
    post:
      consumes:
      - application/json
      description: Registrate new skill for teacher (if he not exists create and registrate
        skill)
      parameters:
      - description: Skill data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/add_skill.request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      security:
      - BearerAuth: []
      summary: Registrate new skill
      tags:
      - teachers
  /teachers:
    get:
      description: Get full teachers data (their user data, teacher data and skills)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/get_teachers.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      security:
      - BearerAuth: []
      summary: Get full teachers data
      tags:
      - teachers
  /teachers/{id}:
    get:
      description: Get all info about teacher (user info + teacher + his skills) by
        user id in route (/api/teachers/{id})
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/get_teacher.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      summary: Get teacher data
      tags:
      - teachers
  /user/profile:
    get:
      description: 'Get info about user by jwt token (in Authorization enter: Bearer
        <your_jwt_token>)'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/get_user.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - users
  /users/{id}/profile:
    get:
      description: Get info about user by user id in route (/api/users/{id}/profile)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/get_user.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/jsonutils.ErrorStruct'
      summary: Get user profile
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
